#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=635071630698
BundleId=mobi.aroha.baccarat3d
ClientId=635071630698.apps.googleusercontent.com

*/

#define kAppID "635071630698"
#define kBundleID "mobi.aroha.baccarat3d"
#define kClientID "635071630698.apps.googleusercontent.com"

#endif


